[project]
name = "diffusion_policy"
version = "1.0.0"
description = "Universal Manipulation Interface - Diffusion Policy Training"
requires-python = ">=3.9,<3.12"
dependencies = [
    "umi", # Depends on workspace sibling
    "diffusers==0.18.2",
    "hydra-core==1.2.0",
    "wandb>=0.15.8",
    "einops>=0.6.1",
    "accelerate==0.24",
    "timm>=0.9.7",
    "scikit-fda>=0.9",
    # Simulation / Gym
    "gym",
    "robomimic==0.2.0",
    "free-mujoco-py==2.1.6",
    "v4l2py==2.2",
    "ur-rtde==1.5.6",
    "atomics==1.0.2",
    "pynput==1.7.6",
    "fastcrc==0.2",
    "lmdb>=1.4",
    "boto3>=1.33",
    "ray[default]==2.8.0",
    "threadpoolctl==3.2",
    "cython>=0.29",
    "ipykernel>=6.23",
    "spnav @ git+https://github.com/cheng-chi/spnav.git@c1c938ebe3cc542db4685e0d13850ff1abfdb943",
    "robosuite @ git+https://github.com/cheng-chi/robosuite.git@3f2c3116f1c0a1916e94bfa28da4d055927d1ab3",
]

[tool.setuptools]
packages = ["diffusion_policy"]

# Fix gym build in this sub-package too
[build-system]
requires = ["setuptools<65", "wheel"]
build-backend = "setuptools.build_meta"
